import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by 2KM',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>
        {children}
        
        </body>
    </html>
  )
}
