"use client"
import { Footer } from './Components/Footer/Footer'
import { Navbar } from './Components/Navbar/Navbar'
import {motion} from "framer-motion"


import './globals.css'
 import type { Metadata } from 'next'


//  export const metadata: Metadata= {
//    title: 'Geekdario | Portfolio',
//    description: 'Generated by 2KM',
// }


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
       
      <body className='relative w-full text-white bg-bg-col '>
        <Navbar/>
        <motion.main initial={{ opacity: 0 }} animate={{ opacity: 100 }}  transition={{ duration: 0.5 }}  >
        {children}
        </motion.main>
        <Footer/>
        
        </body>
    </html>
  )
}
